c_compiler:
  - gcc  # [linux]
  - clang  # [osx]
  - vs2022  # [win]
c_compiler_version:  # [unix]
  - '>=15.2.0'  # [linux]
  - 19  # [osx]
cxx_compiler:
  - gxx  # [linux]
  - vs2022  # [win]
  - clangxx  # [osx]
cxx_compiler_version:  # [unix]
  - '>=15.2.0'  # [linux]
  - 19  # [osx]
microarch_level:
  - 1
  - 3  # [unix and x86_64]
